[build-system]
requires = [
    "setuptools",
    "packaging",
    "oldest-supported-numpy; python_version<='3.8'",
    "numpy>=2.0,<3; python_version>'3.8'",
    "mypy"
]

build-backend = "setuptools.build_meta"
